dataBlocks = [
    'CASE DATA BLOCK',
    'NCP IDENTIFICATION DATA BLOCK',
    'NCP LOCATE DATA BLOCK',
    'PARTICIPANT DATA BLOCK',
    'ORDER DATA BLOCK',
    'COLLECTION DATA BLOCK',
    'INFORMATION DATA BLOCK'
]

